name: Validate documentation site

on:
  pull_request:
    paths:
      # Rebuild when workflow configs change.
      - .github/workflows/validate-documentation.yml
      - '**.md'
      - lint_docs.sh
      - .markdownlint.rb

jobs:
  lint:
    name: Lint Markdown files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@354a1ad156761f5ee2b7b13fa8e09943a5e8d252 # v1.229.0
        with:
          ruby-version: 3.4.2
      - name: Install dependencies
        run: gem install mdl
      - name: Lint docs
        run: ./lint_docs.sh
